---
title: "Homework 5"
output: github_document
author: Na Yun Cho
---

```{r}
library(tidyverse)
```

# Problem 2 

```{r}
df = tibble(files = list.files(path = "./data", full.names = TRUE)) %>%
  mutate(file_contents = map(.x = files, ~read_csv(.x))) %>%
  unnest(file_contents) %>%
  pivot_longer(
    week_1 : week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observations"
  ) %>%
  mutate(files = str_replace(files, ".csv$", "")) %>%
  mutate(files = str_replace(files, "exp", "experimental"),
         files = str_replace(files, "con", "control")) %>%
  separate(files, into = c("arms_old", "id"), sep = "\\_") %>%
  separate(arms_old, into = c("dot", "data", "arm"), sep = "/") %>%
  select(arm, id, week, observations) %>%
  mutate(arm = as.factor(arm), id = as.numeric(id), week = as.numeric(week))
  
df
```

```{r}
plot = df %>%
  ggplot(aes(x = week, y = observations, group = interaction(id, arm), color = arm)) +
  geom_line() + labs(title = "Observations on each subject in experimental and control arms", x = "week", y = "observations")

plot
```




# Problem 3 

### Create a function
```{r}
sim_ttest = function(mu) {
  
  sim_data = tibble(
    x = rnorm(n = 30, mean = mu, sd = 5)
  )
  
  sim_data %>%
    t.test(mu = 0, alternative = "two.sided", conf.level = 0.95) %>%
    broom::tidy() %>%
    select(estimate, p.value)
}

sim_ttest(0)
```

### Simulations 5000 times for mu = 0 
```{r}
sim_mu0 = rerun(5000, sim_ttest(0)) %>%
  bind_rows()

```

### Simulations 5000 times for mu = 1,2,3,4,5,6
```{r}
sim_mus = tibble(mu = c(1,2,3,4,5,6)) %>%
  mutate( 
    output = map(.x = mu, ~rerun(5000, sim_ttest(.x))), 
    estimate= map(output, bind_rows)) %>%
  select(mu, estimate) %>%
  unnest(estimate)
  
```

### Make plots
##### (1) step 1 of making plot 1
```{r}
test_power = 
  sim_mus %>%
  mutate(decision = case_when(
    p.value < 0.05 ~ "rejected", 
    p.value >= 0.05 ~ "fail to reject"
  )) %>%
  group_by(mu) %>%
  summarize(
    total_decision = n(), 
    total_reject = sum(decision == "rejected")
  ) %>%
  mutate(
    prop_tests = map2(.x = total_reject, .y = total_decision, ~prop.test(x = .x, n = .y)), 
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(mu, total_decision, total_reject, tidy_tests) %>%
  unnest(tidy_tests) %>%
  select(mu, estimate, conf.low, conf.high) %>%
  rename(power = estimate)

test_power
```

##### (2) step 2 of making plot 1
```{r}
test_power %>% ggplot(aes(x = mu, y = power)) +
  geom_point() +
  geom_smooth() + 
  labs()
```

